### PR TITLE
Contact  added

### LINKED ISSUE #50: Adding Contact Us Page
I want to add contact us page for this website. Can you attach the hacktoberfest labels and assign me this issue ?

### PR DESCRIPTION
**Pull request by arindam369**
I have added contact page. Please approve my PR.

### CODE REVIEW

**Comment by TheGuyDangerous** [comment]
Thank you 🙂
Be sure to star 🌟 the repo , helps me out 😉.

**Comment by TheGuyDangerous** [comment]
Ah , its wrong again. I asked you to fetch all the changes .
Since your last pr , there were many changes to the website which all get discarded after I merge them.

Hinglish - Index.html page mein kaafi changes hue they , jo tmne update nahi kiya h.
eg.) 
image
animations to the page -
image

Changes update krke push kro

**Comment by TheGuyDangerous** [comment]
current running website k main page ko apne main page se compare kro , pta chal jaayega kya changes hue hai
image
5 commit peeche chal rahe ho

**Comment by TheGuyDangerous** [comment]
simple solution to it , would be - git pull kro terminal mein code editor ke , voh updates fetch kr lega .. vaha se continue

**Comment by arindam369** [comment]
I think now it is fine

**Pull request merged**
