### PR TITLE
Added Progressbar on homepage

### PR DESCRIPTION
**Pull request by himalgnn**
I added progressbar on homepage

Screenshot 2022-10-16 at 5 39 30 PM

### CODE REVIEW

**Comment by TheGuyDangerous** [comment]
Hi there @himalgnn , it appears that a lot of changes have been to the repository (specially on index.html) since you last committed. Hence your branch is not up to date with the main branch.
Update the changes and add this progress bar for all the pages , and we'll be good to go.

**Comment by TheGuyDangerous** [comment]
Thanks for the contribution!!
Please star the repo ✨ , as it helps us out 🤍 
Happy hacking 🙂

**Comment by himalgnn** [comment]
@TheGuyDangerous Most welcome, repo starred ♥️😊 
And also I added progress bar on all existing pages in another pull request. This was only for homepage !

**Comment by TheGuyDangerous** [comment]
@himalgnn yes , merged it as well !✨🙂

**Pull request merged**
