### PR TITLE
Contact added

### PR DESCRIPTION
**Pull request by arindam369**
I have added the Contact page...Kindly attach the hacktoberfest labels and approve my pull request

### CODE REVIEW

**Comment by TheGuyDangerous** [comment]
Thank you for your contribution 😊✨
Make sure to star the repo, as it helps the community grow.
Happy Hacking !!

**Comment by TheGuyDangerous** [comment]
Update the navigation bar properly 
Instead of this menu -
Screenshot_2022_1016_124727

Add another tab , as it looks more minimal 
Screenshot_2022_1016_124658

**Comment by arindam369** [comment]
Okk... I  am looking into it

**Comment by arindam369** [comment]
Can you tell me in which page "contact" is not visible in navbar? I can see it is visible in every pages

**Comment by TheGuyDangerous** [comment]
Hiee !! , sorry 😅 , the issue was from my end with my device's screen size being small.
You can Create a Pull request again , after fetching the latest changes and I'll be happy to merge it.
Again , extremely sorry for the inconvenience 🤍✨.

**Comment by arindam369** [comment]
Oh okay okay 😂... Its okay....Fine,, I am again creating a merge request

**Pull request merged**
