### PR TITLE
Changed sentence phrasing, spellings and grammar

### PR DESCRIPTION
**Pull request by LunarMarathon**

### CODE REVIEW

**Comment by TheGuyDangerous** [comment]
Unnecessary changes

**Comment by LunarMarathon** [comment]
@TheGuyDangerous Why have you added the spam tag? 
image

Go through the changes:

1. The spelling of desserts is wrong
2. Curated and selected mean the same
3. Platform is spelled wrong
4. Few words were capitalized in the middle of the sentences

**Comment by TheGuyDangerous** [comment]
Adding punctuations and capitalizing words are not required at the moment, hence considered spammy and invalid.
If you still felt the need , you should've created an issue requesting punctuation changes and if accepted, get them assigned to work on.

**Comment by LunarMarathon** [comment]
I noticed these so I edited and opened a PR. I'm not trying to spam in any manner. The maintainers can review and let the contributor know if they want certain lines to remain as it is. I've mentioned everything else as issues, these would require many screenshots to confirm first and then change so only for the textual ones, I directly changed and opened a PR. You can just close the PR if you don't require it. I've already finished my 4 PRs for hacktoberfest and was just contributing. Please remove the tag

**Comment by LunarMarathon** [comment]
There are spelling mistakes

**Comment by TheGuyDangerous** [comment]
Be sure that , 

> I noticed these so I edited and opened a PR. I'm not trying to spam in any manner. The maintainers can review and let the contributor know if they want certain lines to remain as it is. I've mentioned everything else as issues, these would require many screenshots to confirm first and then change so only for the textual ones, I directly changed and opened a PR. You can just close the PR if you don't require it. I've already finished my 4 PRs for hacktoberfest and was just contributing. Please remove the tag

Be careful for what you are contributing to , I won't be accepting low quality contributions , and these go against the guidelines of Hacktoberfest :)
Kindly contribute for genuine reasons , and not for a mere T-shirt

**Comment by LunarMarathon** [comment]
You can take a look at my profile and my PRs. I have made sure not to contribute to DSA repos and list based repos which go against the guidelines of HF. HF also allows non-tech contributions this time. None of my PRs have been excluded. So, I'm mindful about my contributions. If you don't require non-code contributions, please mention them in the contributing file so that others don't have to go through this

These come under copy editing - 
image

**Comment by LunarMarathon** [comment]
@TheGuyDangerous Why have you labelled it as spam again?

**Pull request merged**
